minimumReleaseAge: 1440

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true

catalog:
  dompurify: ^3.4.12
  echarts: ^6.1.0
  vite: ^8.1.5
  vue: ^2.7.16

overrides:
  dompurify: 'catalog:'
  echarts: 'catalog:'
  glob: ^13.0.6
  serialize-javascript: ^7.0.3
  vite: 'catalog:'
  vue: 'catalog:'
  '@originjs/vite-plugin-content>xlsx': '-'
