minimumReleaseAge: 1440

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true

catalog:
  dompurify: ^3.4.13
  echarts: ^6.1.0
  typescript: npm:typescript-native-bridge@6.0.3-bridge.7.tsgo.7.0.2
  vite: ^8.2.1
  vue: ^2.7.16

overrides:
  dompurify: 'catalog:'
  echarts: 'catalog:'
  glob: ^13.0.6
  serialize-javascript: ^7.0.3
  typescript: 'catalog:'
  vite: 'catalog:'
  vue: 'catalog:'
  '@originjs/vite-plugin-content>xlsx': '-'
