name: Bug report
description: Create a report to help us improve
labels: ["GH - Bug", "GH - Evaluation Needed"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Thank you for using Fluidd and taking the time to report bugs! ✨

        #### This form is ONLY for reporting bugs related to Fluidd!

        - If you have a feature request, please use [feature_request](new?template=feature_request.yml)
        - If you need any other help, please visit the [Fluidd Discord](https://discord.gg/GZ3D5tqfcF/)

        ---
  - type: input
    id: version
    attributes:
      label: Fluidd Version
      description: >-
        Fluidd version you were using when you experienced this issue (as shown in bottom right corner of the page, eg. v1.31.3-bc79728)
      placeholder: >-
        <your current Fluidd version>
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: >-
        In which browser did you experience this issue (please select all that apply)?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (Please tell us below)
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: >-
        In what kind of device did you experience this issue (please select all that apply)?
      multiple: true
      options:
        - Desktop PC
        - Laptop
        - Mobile device (Phone, Tablet or similar)
        - Other (Please tell us below)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: >-
        What operating system runs on the device where you experienced this issue (please select all that apply)?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other (Please tell us below)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen
      description: >-
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce
      description: >-
        Minimal and precise steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us, use the field below.

        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
