name: Bug report
description: Create a report to help us improve
labels: ["GH - Bug", "GH - Evaluation Needed"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
        If you have a feature request, please use [feature_request](new?template=feature_request.yml)
  - type: input
    id: version
    attributes:
      label: Fluidd Version
      description: >-
        Fluidd version where the issue occurs
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: >-
        The browser you are using to access Fluidd
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (Please tell us below)
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: >-
        The type of device you are using
      multiple: true
      options:
        - Desktop PC
        - Laptop
        - Mobile device (Phone, Tablet or similar)
        - Other (Please tell us below)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: >-
        The operating system powering your device
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other (Please tell us below)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen
      description: >-
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce
      description: >-
        Minimal and precise steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us, use the field below.

        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
