name: Feature Request
description: Have a cool feature in mind? Use this template!
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for feature requests only!
        If you've found a bug, please use [bug_report](/new?template=bug_report.yml)
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: >-
        A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: >-
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: possible-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: >-
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us, use the field below.

        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
