[project]
site_name = "Fluidd"
site_url = "https://docs.fluidd.xyz"
site_description = "A web interface for Klipper 3D printer firmware"
copyright = "&copy; Fluidd 2026"
repo_url = "https://github.com/fluidd-core/fluidd"
repo_name = "fluidd-core/fluidd"
edit_uri = "edit/main/docs/docs/"
site_dir = "site"
extra_css = ["stylesheets/extra.css"]

nav = [
  {"Home" = "index.md"},
  {"Installation" = "installation.md"},
  {"Configuration" = "configuration.md"},
  {"Customize" = "customize.md"},

  {"Features" = [
    "features/authorization.md",
    "features/bed-mesh.md",
    "features/cameras.md",
    "features/console.md",
    "features/diagnostics.md",
    "features/gcode-viewer.md",
    "features/integrations.md",
    "features/localization.md",
    "features/macros.md",
    "features/multiple-extruders.md",
    "features/multiple-printers.md",
    "features/notifications.md",
    "features/obico.md",
    "features/octoeverywhere.md",
    "features/print-history.md",
    "features/sensors.md",
    "features/slicer-uploads.md",
    "features/spoolman.md",
    "features/system.md",
    "features/thermal-chart.md",
    "features/thermal-presets.md",
    "features/thumbnails.md",
    "features/timelapse.md",
    "features/updates.md"
  ]},
  {"Development" = "development.md"},
  {"FAQ" = "faq.md"},
  {"Sponsors" = "sponsors.md"}
]

[project.theme]
variant = "modern"
logo = "assets/images/fluidd_icon.svg"
favicon = "favicon.ico"
features = [
  "content.action.edit",
  "content.code.copy",
  "navigation.path",
  "navigation.instant",
  "navigation.instant.progress",
  "navigation.top"
]
custom_dir = "overrides"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.attr_list]
[project.markdown_extensions."pymdownx.keys"]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/fluidd-core/fluidd"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/GZ3D5tqfcF"
